/* Actions possibles de l'archer */
export enum Action {
  ADVANCE = 'ADVANCE',
  ROTATE_LEFT = 'ROTATE_LEFT',
  ROTATE_RIGHT = 'ROTATE_RIGHT',
  ORIENT_NORTH = 'ORIENT_NORTH',
  ORIENT_SOUTH = 'ORIENT_SOUTH',
  ORIENT_EAST = 'ORIENT_EAST',
  ORIENT_WEST = 'ORIENT_WEST',
  SHOOT = 'SHOOT',
  EXIT = 'EXIT',
}
