export enum Direction {
  NORTH = 'NORTH',
  EAST = 'EAST',
  SOUTH = 'SOUTH',
  WEST = 'WEST',
}

export enum Action {
  ADVANCE = 'ADVANCE',
  ROTATE_LEFT = 'ROTATE_LEFT',
  ROTATE_RIGHT = 'ROTATE_RIGHT',
  MOVE_NORTH = 'MOVE_NORTH',
  MOVE_SOUTH = 'MOVE_SOUTH',
  MOVE_EAST = 'MOVE_EAST',
  MOVE_WEST = 'MOVE_WEST',
  ORIENT_NORTH = 'ORIENT_NORTH',
  ORIENT_SOUTH = 'ORIENT_SOUTH',
  ORIENT_EAST = 'ORIENT_EAST',
  ORIENT_WEST = 'ORIENT_WEST',
  SHOOT = 'SHOOT',
  EXIT = 'EXIT',
}

export enum Perception {
  STENCH = 'STENCH',
  BREEZE = 'BREEZE',
  GLIMMER = 'GLIMMER',
  BUMP = 'BUMP',
  SCREAM = 'SCREAM',
}

export enum GameStatus {
  PLAYING = 'PLAYING',
  WON = 'WON',
  LOST = 'LOST',
}
